<a href="https://colab.research.google.com/github/almasfiza/ML-DLShow/blob/master/Q2Day3_ALMAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Using digits dataset to implement SVM

In [8]:
#import the pandas and the data set 
import pandas as pd
from sklearn.datasets import load_digits
digits = load_digits()

In [9]:
#features present in the dataset
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [10]:
#features in the dataset- images

digits.images

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.],
        ...,
        [ 0.,  0., 16., ..., 15.,  0.,  0.],
        [ 0.,  0., 15., ..., 16.,  0.,  0.],
        [ 0.,  0.,  2., ...,  6.,  0.,  0.]],

       [[ 0.,  0.,  2., ...,  0.,  0.,  0.],
        [ 0.,  0., 14., ..., 15.,  1.,  0.],
        [ 0.,  4., 16., ..., 16.,  7.,  0.],
        ...,
        [ 0.,  0.,  0., ..., 16.,  2.,  0.],
        [ 0.,  0.,  4., ..., 16.,  2.,  0.],
        [ 0.,  0.,  5., ..., 12.,  0.,  0.]],

       [[ 0.,  0., 10., ...,  1.,  0.,  0.],
        [ 0.,  2., 16., ...,  1.,  0.,  0.],
        [ 0.,  0., 15., ..., 15.,  0.,  0.],
        ...,
        [ 0.,  4., 16., ..., 16.,  6.,  0.],
        [ 0.,  8., 16., ..., 16.,  8.,  0.],
        [ 0.,  1.,  8., ..., 12.,  1.,  0.]]])

Reshaping the data to 1d

In [12]:
n = len(digits.images)
print(n)

1797

In [13]:
data = digits.images.reshape((n,-1))
print(data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]

In [14]:
#create a dataframe for better visualisation using reshaping for array flattening
df = pd.DataFrame(data)
df.head(10)

    0    1     2     3     4     5   ...    58    59    60    61   62   63
0  0.0  0.0   5.0  13.0   9.0   1.0  ...   6.0  13.0  10.0   0.0  0.0  0.0
1  0.0  0.0   0.0  12.0  13.0   5.0  ...   0.0  11.0  16.0  10.0  0.0  0.0
2  0.0  0.0   0.0   4.0  15.0  12.0  ...   0.0   3.0  11.0  16.0  9.0  0.0
3  0.0  0.0   7.0  15.0  13.0   1.0  ...   7.0  13.0  13.0   9.0  0.0  0.0
4  0.0  0.0   0.0   1.0  11.0   0.0  ...   0.0   2.0  16.0   4.0  0.0  0.0
5  0.0  0.0  12.0  10.0   0.0   0.0  ...   9.0  16.0  16.0  10.0  0.0  0.0
6  0.0  0.0   0.0  12.0  13.0   0.0  ...   1.0   9.0  15.0  11.0  3.0  0.0
7  0.0  0.0   7.0   8.0  13.0  16.0  ...  13.0   5.0   0.0   0.0  0.0  0.0
8  0.0  0.0   9.0  14.0   8.0   1.0  ...  11.0  16.0  15.0  11.0  1.0  0.0
9  0.0  0.0  11.0  12.0   0.0   0.0  ...   9.0  12.0  13.0   3.0  0.0  0.0

[10 rows x 64 columns]

Implementing SVM

In [15]:
from matplotlib import pyplot as plt
from sklearn import datasets, svm, metrics
from sklearn.model_selection import train_test_split

In [17]:
%matplotlib inline

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [31]:
from sklearn.svm import SVC
model = SVC( gamma=0.001)
# higher C lower gamma
#higher value of regulaisation
#linear kernel more accuracy

In [32]:
#calling fit() to train the model
model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [33]:
model.score(X_test,y_test)

0.9851851851851852